@startuml sushi
 hide circle
 skinparam linetype ortho
 
 entity "ネタ (items)" as items {
     * <<PK>> id : int : ID
     --
     * name : string : 名称
 }

 entity "メニューとアイテムの中間テーブル (menus_items)" as menus_items {
     * <<PK>> id : int : ID
     --
     * <<FK>> menu_id : int : メニューID
     * <<FK>> item_id : int : アイテムID
     * quantity : int : メニュー内のアイテム個数
 }

 entity "メニュー (menus)" as menus {
     * <<PK>> id : int : ID
     --
     * <<FK>> menu_type_id : int : メニュー種別ID
     * <<FK>> menu_label_id : int : メニューラベルID
     * name : string : メニュー名
     * price : int : 値段
     * can_be_taken_away : boolean : 持ち帰り可否
 }

 entity "メニュー種別 (menu_types)" as menu_types {
     * <<PK>> id : int : ID
     --
     * <<u>> name : string : 名称
 }

 entity "メニューラベル (menu_labels)" as menu_labels {
     * <<PK>> id : int : メニューラベルID
     --
     * <<u>> label : string : メニューラベル
 }

 entity "顧客 (customers)" as customers {
     * <<PK>> id : int : ID
     --
     * name : string : 名前
     * phone_number : string : 電話番号
 }

 entity "シャリサイズ種別 (rice_size_types)" as rice_size_types {
     * <<PK>> id : int : ID
     --
     * name : string : 名称
 }

entity "来店 (visits)" as visits {
     * <<PK>> id : int : ID
    --
     * <<FK>> customer_id : int : 顧客ID
     * is_eat_in : boolean : 店内か持ち帰りか否か
     * visited_at : date : 来店日時
}

entity "注文 (orders)" as orders {
     * <<PK>> id : int : ID
     --
     * <<FK>> visit_id : int : 来店ID
     * memo : string : 顧客記入メモ欄
     * ordered_at : date : 注文日時
}

entity "会計 (payments)" as payments {
     * <<PK>> id : int : ID
     --
     * <<FK>> visit_id : int : 来店ID
     * total_price: int : 合計金額
     * paid_at : date : 会計日時
}

 entity "注文詳細 (order_details)" as order_details {
     * <<FK>> order_id : int : 注文ID
     * <<FK>> menu_id : int : メニューID
     --
     * quantity: int : 注文個数
     * has_mustard: boolean : サビ要否
     * rice_size_type_id: int : シャリサイズ種別
 }

 entity "アイテム別月間売上 (monthly_sales_per_item)" as monthly_sales_per_item {
     * <<FK>> item_id : int : アイテムID
     * month : int : 月
     * is_eat_in : boolean : 店内か持ち帰りか否か
     * includes_set_menu : boolean : セットメニュー内アイテム個数を集計対象とするか否か
     --
     * quantity: int : 個数
     * price : int : 金額
 }

customers ||..o{ visits
visits ||..o| payments
visits ||..|{ orders
orders ||..|{ order_details
rice_size_types ||..o| order_details
menus ||..o{ order_details
menu_types ||..o{ menus
menu_labels |o..o{ menus
menus ||..o{ menus_items
items ||..o{ menus_items
items ||..o{ monthly_sales_per_item

 @enduml
