@startuml sushi
 hide circle
 skinparam linetype ortho
 
 entity "管理者 (administrators)" as administrators {
     * <<PK>> id : int : ID
     --
     * name : int : 名称
     * can_modify_administrators : boolean : 管理者編集権限有無
     * can_modify_items : boolean : アイテム編集権限有無
     * can_modify_menus : boolean : メニュー編集権限有無
     * can_modify_customers : boolean : 顧客編集権限有無
 }

 entity "編集履歴 (modification_histories)" as modification_histories {
     * <<PK>> id : int : ID
     --
     * modified_at : date : 編集時刻
 }

  entity "管理者編集履歴 (administrators_histories)" as administrators_histories {
     * <<PK>> id : int : ID
     --
     * <<FK>> modification_history_id : int : 編集履歴ID
     * <<FK>> administrator_id : int : 管理者ID
     * <<FK>> name : int : 管理者名称
     * <<FK>> can_modify_administrators : boolean : 管理者編集権限有無
     * <<FK>> can_modify_items : boolean : アイテム編集権限有無
     * <<FK>> can_modify_menus : boolean : メニュー編集権限有無
     * <<FK>> can_modify_customers : boolean : 顧客編集権限有無
 }

 entity "ネタ (items)" as items {
     * <<PK>> id : int : ID
     --
     * name : string : 名称
 }

 entity "ネタ編集履歴 (items_histories)" as items_histories {
     * <<PK>> id : int : ID
     --
     * <<FK>> modification_history_id : int : 編集履歴ID
     * <<FK>> item_id : string : アイテムID
     * <<FK>> name : string : アイテム名称
 }

 entity "メニューとアイテムの中間テーブル編集履歴 (menus_items_histories)" as menus_items_histories {
     * <<PK>> id : int : ID
     --
     * <<FK>> modification_history_id : int : 編集履歴ID
     * <<FK>> menu_item_id : int : メニューとアイテムの中間テーブルID
     * <<FK>> menu_id : int : メニューID
     * <<FK>> item_id : int : アイテムID
     * <<FK>> menu_item_quantity : int : メニュー内のアイテム個数
 }

 entity "メニューとアイテムの中間テーブル (menus_items)" as menus_items {
     * <<PK>> id : int : ID
     --
     * <<FK>> menu_id : int : メニューID
     * <<FK>> item_id : int : アイテムID
     * <<FK>> quantity : int : メニュー内のアイテム個数
 }

 entity "メニュー編集履歴 (menus_histories)" as menus_histories {
     * <<PK>> id : int : ID
     --
     * <<FK>> modification_history_id : int : 編集履歴ID
     * <<FK>> menu_id : int : ID
     * <<FK>> menu_type_id : int : メニュー種別ID
     <<FK>> menu_label_id : int : メニューラベルID
     * <<FK>> name : string : メニュー名
     * <<FK>> price : int : メニュー価格
     * <<FK>> can_be_taken_away : boolean : 持ち帰り可否
 }

 entity "メニュー (menus)" as menus {
     * <<PK>> id : int : ID
     --
     * <<FK>> menu_type_id : int : メニュー種別ID
     <<FK>> menu_label_id : int : メニューラベルID
     * name : string : メニュー名
     * price : int : 値段
     * can_be_taken_away : boolean : 持ち帰り可否
 }

 entity "メニュー種別 (menu_types)" as menu_types {
     * <<PK>> id : int : ID
     --
     * <<u>> name : string : 名称
 }

 entity "メニューラベル (menu_labels)" as menu_labels {
     * <<PK>> id : int : メニューラベルID
     --
     * <<u>> label : string : メニューラベル
 }

 entity "顧客編集履歴 (customers_histories)" as customers_histories {
     * <<PK>> id : int : ID
     --
     * <<FK>> customer_id : int : 顧客ID
     * <<FK>> name : string : 名前
     * <<FK>> phone_number : int : 電話番号
 }

 entity "顧客 (customers)" as customers {
     * <<PK>> id : int : ID
     --
     * name : string : 名前
     * phone_number : int : 電話番号
 }

 entity "シャリサイズ種別 (rise_size_types)" as rise_size_types {
     * <<PK>> id : int : ID
     --
     * name : string : 名称
 }

entity "注文 (orders)" as orders {
     * <<PK>> id : int : ID
     --
     <<FK>> payment_id : int : 会計ID
     * is_eat_in : boolean : 店内か持ち帰りか否か
     * memo : string : 顧客記入メモ欄
     * ordered_at : date : 注文日時
}

entity "会計 (payments)" as payments {
     * <<PK>> id : int : ID
     --
     * <<FK>> customer_id : int : 顧客ID
     * total_price: int : 合計金額
     * paid_at : date : 会計日時
}

 entity "注文詳細 (order_details)" as order_details {
     * <<FK>> order_id : int : 注文ID
     * <<FK>> menu_id : int : メニューID
     --
     * quantity: int : 注文個数
     * has_mustard: boolean : サビ要否
     * rise_size_type_id: int : シャリサイズ種別
 }

 entity "アイテム別月間売上 (monthly_sales_per_item)" as monthly_sales_per_item {
     * <<FK>> item_id : int : アイテムID
     * month : int : 月
     * is_eat_in : boolean : 店内か持ち帰りか否か
     * includes_set_menu : boolean : セットメニュー内アイテム個数を集計対象とするか否か
     --
     * quantity: int : 個数
     * price : int : 金額
 }

customers ||..o{ payments
payments |o..|{ orders
orders ||..|{ order_details
rise_size_types ||..o| order_details
menus ||..o{ order_details
menu_types ||..o{ menus
menu_labels |o..o{ menus
menus ||..o{ menus_items
items ||..o{ menus_items
items ||..o{ monthly_sales_per_item
administrators ||..o{ modification_histories
modification_histories ||..o{ administrators_histories
modification_histories ||..o{ items_histories
modification_histories ||..o{ menus_items_histories
modification_histories ||..o{ menus_histories
modification_histories ||..o{ customers_histories
administrators ||..o{ administrators_histories
items ||..o{ items_histories
menus_items ||..o{ menus_items_histories
menus ||..o{ menus_histories
customers ||..o{ customers_histories

 @enduml
